#!/usr/bin/env python3
"""Generate thin local adapters that route AI hosts to canonical SecWeaver Skills."""

from __future__ import annotations

import argparse
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATED_MARKER = "<!-- Generated by SecWeaver ai-setup; edit src/skills instead. -->"


@dataclass(frozen=True)
class HostAdapter:
    """Describe one host's repository-local discovery path and adapter format."""

    path: str
    kind: str
    display_name: str


HOSTS: dict[str, HostAdapter] = {
    "codex": HostAdapter(".agents/skills/secweaver/SKILL.md", "skill", "Codex"),
    "cursor": HostAdapter(".cursor/rules/secweaver-skills.mdc", "cursor", "Cursor"),
    "claude": HostAdapter(".claude/skills/secweaver/SKILL.md", "skill", "Claude Code"),
    "openclaw": HostAdapter("skills/secweaver/SKILL.md", "skill", "OpenClaw"),
    "workbuddy": HostAdapter(".workbuddy/skills/secweaver/SKILL.md", "workbuddy", "WorkBuddy"),
}

ROUTER_BODY = """# SecWeaver Skill Router

This adapter contains no SecWeaver Skill implementation. The canonical Skill root is
`src/skills/` in this repository.

When a request concerns security alert confirmation, traceability, risk identification,
data-source completeness, evidence fetching, log-format discovery, DataAsset guidance,
or an offline SecWeaver showcase:

1. Work from the repository root and read `src/skills/README.md`.
2. Select the smallest matching workflow from that index. For an offline demo or
   quick product experience, select `src/skills/offline-showcase/SKILL.md`.
3. Read the selected `src/skills/<name>/SKILL.md` completely before acting.
4. Resolve references relative to the selected canonical Skill directory and run its scripts
   from the repository root.
5. Keep plaintext credentials out of prompts and Skill files; pass only documented
   `credentials_ref` values.

Never copy Skill instructions into this adapter. Changes belong under `src/skills/` so every
host uses the same workflow source.
"""


def render_adapter(host: str) -> str:
    """Render host metadata around the shared router without copying canonical Skill content."""
    adapter = HOSTS[host]
    if adapter.kind == "cursor":
        return (
            "---\n"
            "description: Route security operations requests to canonical SecWeaver Skills under src/skills.\n"
            "globs:\n"
            "alwaysApply: false\n"
            "---\n\n"
            f"{GENERATED_MARKER}\n\n{ROUTER_BODY}"
        )
    if adapter.kind == "workbuddy":
        return (
            "---\n"
            "name: secweaver\n"
            "display_name: SecWeaver Security Operations\n"
            "display_name_en: SecWeaver Security Operations\n"
            "description: Route local security operations tasks to canonical SecWeaver Skills.\n"
            "description_zh: 将本地安全运营任务路由到 SecWeaver 的规范 Skill。\n"
            "description_en: Route local security operations tasks to canonical SecWeaver Skills.\n"
            "version: 1.0.0\n"
            "author: SecWeaver Community\n"
            "---\n\n"
            f"{GENERATED_MARKER}\n\n{ROUTER_BODY}"
        )
    return (
        "---\n"
        "name: secweaver\n"
        "description: Route security operations requests to canonical SecWeaver Skills under src/skills.\n"
        "---\n\n"
        f"{GENERATED_MARKER}\n\n{ROUTER_BODY}"
    )


def validate_repo_root(root: Path) -> None:
    """Reject the wrong working tree before any host configuration is created."""
    skill_index = root / "src/skills/README.md"
    skill_files = list((root / "src/skills").glob("*/SKILL.md"))
    if not skill_index.is_file() or not skill_files:
        raise ValueError(f"not a SecWeaver repository root: {root}")


def write_adapter(path: Path, content: str) -> str:
    """Create or atomically refresh generated content without overwriting user-owned files."""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return "unchanged"
        if GENERATED_MARKER not in existing:
            raise FileExistsError(f"refusing to overwrite non-SecWeaver host configuration: {path}")
        action = "updated"
    else:
        action = "created"

    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as handle:
        temporary = Path(handle.name)
        handle.write(content)
    try:
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)
    return action


def setup_host(host: str, root: Path) -> tuple[str, Path]:
    """Install one repository-local adapter and return its action and relative path."""
    return setup_hosts(host, root)[0]


def setup_hosts(host: str, root: Path) -> list[tuple[str, Path]]:
    """Install one or all adapters after checking that no user-owned file is at risk.

    The all-host path preflights every destination before writing. This prevents a
    later conflict from leaving a partially configured checkout.
    """
    resolved_root = root.expanduser().resolve()
    validate_repo_root(resolved_root)
    selected_hosts = sorted(HOSTS) if host == "all" else [host]
    plans = [
        (selected_host, Path(HOSTS[selected_host].path), render_adapter(selected_host))
        for selected_host in selected_hosts
    ]

    for _, relative_path, content in plans:
        destination = resolved_root / relative_path
        if not destination.exists():
            continue
        existing = destination.read_text(encoding="utf-8")
        if existing != content and GENERATED_MARKER not in existing:
            raise FileExistsError(
                f"refusing to overwrite non-SecWeaver host configuration: {destination}"
            )

    return [
        (write_adapter(resolved_root / relative_path, content), relative_path)
        for _, relative_path, content in plans
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a thin AI-host adapter that references canonical src/skills content."
    )
    parser.add_argument("--host", required=True, choices=["all", *sorted(HOSTS)])
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    try:
        results = setup_hosts(args.host, args.root)
    except (FileExistsError, OSError, UnicodeError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1

    selected_hosts = sorted(HOSTS) if args.host == "all" else [args.host]
    for selected_host, (action, path) in zip(selected_hosts, results, strict=True):
        print(f"{action}: {path}")
        print(f"host: {HOSTS[selected_host].display_name}")
    print("canonical skills: src/skills/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
