#!/usr/bin/env bash
set -euo pipefail

# Download the vendor installer at release time. Do not commit the mutable vendor
# script into the repository; publish the generated output directory instead.
: "${OUTPUT_DIR:?OUTPUT_DIR must point to the public logtail release directory}"
: "${PUBLIC_BASE_URL:?PUBLIC_BASE_URL must be the HTTPS public origin}"

REGION="${LOGTAIL_REGION:-cn-hangzhou-internet}"
case "${REGION}" in
  hangzhou)
    REGION="cn-hangzhou"
    ;;
esac
# The vendor selector controls runtime download/upload networking. OSS source
# naming uses the geographic region only, never the '-internet' selector suffix.
SOURCE_REGION="${LOGTAIL_SOURCE_REGION:-${REGION%-internet}}"
[[ "${SOURCE_REGION}" =~ ^[a-z0-9][a-z0-9-]{1,31}$ ]] || { echo "invalid LOGTAIL_SOURCE_REGION" >&2; exit 1; }
SOURCE_URL="${LOGTAIL_SOURCE_URL:-https://logtail-release-${SOURCE_REGION}.oss-${SOURCE_REGION}.aliyuncs.com/linux64/logtail.sh}"

[[ "${PUBLIC_BASE_URL}" =~ ^https:// ]] || {
  echo "PUBLIC_BASE_URL must use HTTPS" >&2
  exit 1
}
[[ "${SOURCE_URL}" =~ ^https:// ]] || {
  echo "LOGTAIL_SOURCE_URL must use HTTPS" >&2
  exit 1
}
[[ "${SOURCE_URL}" != *[[:space:]]* && "${SOURCE_URL}" != *\?* && "${SOURCE_URL}" != *\#* ]] || {
  echo "invalid LOGTAIL_SOURCE_URL" >&2
  exit 1
}

command -v curl >/dev/null 2>&1 || {
  echo "curl is required" >&2
  exit 1
}
if command -v sha256sum >/dev/null 2>&1; then
  SHA256_COMMAND=(sha256sum)
else
  SHA256_COMMAND=(shasum -a 256)
fi

mkdir -p "${OUTPUT_DIR}"
temp_dir="$(mktemp -d)"
trap 'rm -rf "${temp_dir}"' EXIT INT TERM

installer_path="${temp_dir}/install.sh"
curl --fail --location --proto '=https' --tlsv1.2 --silent --show-error \
  --proto-redir '=https' --connect-timeout 10 --max-time 120 \
  --retry 2 --retry-delay 2 --retry-max-time 260 \
  --output "${installer_path}" "${SOURCE_URL}" || {
    echo "stage=publish-logtail-installer download failed; check source DNS/proxy/HTTPS reachability: ${SOURCE_REGION}" >&2
    exit 1
  }

[[ -s "${installer_path}" ]] || {
  echo "downloaded installer is empty" >&2
  exit 1
}
head -c 2 "${installer_path}" | cmp -s - <(printf '#!') || {
  echo "downloaded file is not a shell installer" >&2
  exit 1
}
bash -n "${installer_path}"

digest="$("${SHA256_COMMAND[@]}" "${installer_path}" | awk '{print tolower($1)}')"
install -m 0644 "${installer_path}" "${OUTPUT_DIR}/install.sh"
printf '%s  install.sh\n' "${digest}" >"${OUTPUT_DIR}/install.sh.sha256"
chmod 0644 "${OUTPUT_DIR}/install.sh.sha256"

cat >"${OUTPUT_DIR}/release.env" <<EOF
# Generated by publish-logtail-installer.sh. Source: ${SOURCE_URL}
EOF
printf 'export BOOTSTRAP_LOGTAIL_INSTALL_URL=%q\n' "${PUBLIC_BASE_URL%/}/logtail/install.sh" >>"${OUTPUT_DIR}/release.env"
printf 'export BOOTSTRAP_LOGTAIL_INSTALL_SHA256=%q\n' "${digest}" >>"${OUTPUT_DIR}/release.env"
printf 'export BOOTSTRAP_LOGTAIL_REGION=%q\n' "${REGION}" >>"${OUTPUT_DIR}/release.env"
chmod 0644 "${OUTPUT_DIR}/release.env"

echo "published ${OUTPUT_DIR}/install.sh"
echo "source=${SOURCE_URL}"
echo "sha256=${digest}"
echo "bootstrap environment: ${OUTPUT_DIR}/release.env"
