// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type processLifecycleProcessEvent struct {
	Type        uint32
	RootPid     uint32
	Pid         uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Argc        uint32
	Flags       uint32
	TimestampNs uint64
	Comm        [16]int8
	Filename    [256]int8
	Args        [16][96]int8
}

type processLifecycleProcessOwner struct {
	RootPid   uint32
	ParentPid uint32
	Flags     uint32
}

// loadProcessLifecycle returns the embedded CollectionSpec for processLifecycle.
func loadProcessLifecycle() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessLifecycleBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load processLifecycle: %w", err)
	}

	return spec, err
}

// loadProcessLifecycleObjects loads processLifecycle and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processLifecycleObjects
//	*processLifecyclePrograms
//	*processLifecycleMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessLifecycleObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcessLifecycle()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processLifecycleSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processLifecycleSpecs struct {
	processLifecycleProgramSpecs
	processLifecycleMapSpecs
}

// processLifecycleSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processLifecycleProgramSpecs struct {
	HandleExecve       *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleExecveExit   *ebpf.ProgramSpec `ebpf:"handle_execve_exit"`
	HandleExecveat     *ebpf.ProgramSpec `ebpf:"handle_execveat"`
	HandleExecveatExit *ebpf.ProgramSpec `ebpf:"handle_execveat_exit"`
	HandleProcessExec  *ebpf.ProgramSpec `ebpf:"handle_process_exec"`
	HandleProcessExit  *ebpf.ProgramSpec `ebpf:"handle_process_exit"`
	HandleProcessFork  *ebpf.ProgramSpec `ebpf:"handle_process_fork"`
}

// processLifecycleMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processLifecycleMapSpecs struct {
	PendingExecs     *ebpf.MapSpec `ebpf:"pending_execs"`
	ProcessEvents    *ebpf.MapSpec `ebpf:"process_events"`
	ScratchEvents    *ebpf.MapSpec `ebpf:"scratch_events"`
	TrackedProcesses *ebpf.MapSpec `ebpf:"tracked_processes"`
}

// processLifecycleObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessLifecycleObjects or ebpf.CollectionSpec.LoadAndAssign.
type processLifecycleObjects struct {
	processLifecyclePrograms
	processLifecycleMaps
}

func (o *processLifecycleObjects) Close() error {
	return _ProcessLifecycleClose(
		&o.processLifecyclePrograms,
		&o.processLifecycleMaps,
	)
}

// processLifecycleMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessLifecycleObjects or ebpf.CollectionSpec.LoadAndAssign.
type processLifecycleMaps struct {
	PendingExecs     *ebpf.Map `ebpf:"pending_execs"`
	ProcessEvents    *ebpf.Map `ebpf:"process_events"`
	ScratchEvents    *ebpf.Map `ebpf:"scratch_events"`
	TrackedProcesses *ebpf.Map `ebpf:"tracked_processes"`
}

func (m *processLifecycleMaps) Close() error {
	return _ProcessLifecycleClose(
		m.PendingExecs,
		m.ProcessEvents,
		m.ScratchEvents,
		m.TrackedProcesses,
	)
}

// processLifecyclePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessLifecycleObjects or ebpf.CollectionSpec.LoadAndAssign.
type processLifecyclePrograms struct {
	HandleExecve       *ebpf.Program `ebpf:"handle_execve"`
	HandleExecveExit   *ebpf.Program `ebpf:"handle_execve_exit"`
	HandleExecveat     *ebpf.Program `ebpf:"handle_execveat"`
	HandleExecveatExit *ebpf.Program `ebpf:"handle_execveat_exit"`
	HandleProcessExec  *ebpf.Program `ebpf:"handle_process_exec"`
	HandleProcessExit  *ebpf.Program `ebpf:"handle_process_exit"`
	HandleProcessFork  *ebpf.Program `ebpf:"handle_process_fork"`
}

func (p *processLifecyclePrograms) Close() error {
	return _ProcessLifecycleClose(
		p.HandleExecve,
		p.HandleExecveExit,
		p.HandleExecveat,
		p.HandleExecveatExit,
		p.HandleProcessExec,
		p.HandleProcessExit,
		p.HandleProcessFork,
	)
}

func _ProcessLifecycleClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed processlifecycle_bpfel.o
var _ProcessLifecycleBytes []byte
