creation_rules:
  - path_regex: secrets/.*\.enc\.yaml$
    encrypted_regex: '^(access_key_secret|secret_access_key|password|private_key|token|access_token|api_key|api_secret|security_token|session_token|client_secret|secret_key|key_value|app_key|keytab)$'
    age: REPLACE_WITH_YOUR_AGE_PUBLIC_KEY
