creation_rules:
  - path_regex: secrets/.*\.enc\.yaml$
    encrypted_regex: '^(access_key_secret|secret_access_key|password|private_key|token|access_token|api_key|api_secret|security_token|session_token|client_secret|secret_key|key_value|app_key|keytab)$'
    age: age197mw3g6zf8qrme5ztkp730ndxtu30n8a0w2aljsn9uctxtmu2qgqjans2y
